# Application: Preformance dashboard 
# This is a template of configuration file. In must not be modified.
#
# This file will be loaded at application start in case when application started without command line parameters
# (or with parameters set to default values: performance-dashboard -config-path=./profiles -profile=default)
#
# Application server location
server:
  host: localhost
  port: 45800

# Jira connection requisites
jira:
  url: https://jira.atlassian.com
  projectKey: TEMPLATE
  boardId: 1
  auth:
    type: basic
    clientId: jira-api-access@yourdomain.com
    apiToken: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# HTTP client configuration
httpClient:
  requestTimeout: 30s
  requestRateLimit: 10
  retryLimit: 2

# PostgreSQL database connection requisites
database:
  node:
    - host: localhost
      port: 5432
      db_name: performance-dashboard
      user: app-user
      password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      ssl_mode: disable

# Logging configuration
logger:
  file:
    filename:   /var/log/performance-dashboard/performance-dashboard.log
    maxsize:    10
    maxbackups: 10
    maxage:     30
    compress:   true
  console:
    mode: off   # stdout, stderr or off

# Periodic tasks configuration
schedule:
  task:
    - id: jira_project
      executeOnStartup: true
      period: 1h
    - id: jira_sprint
      executeOnStartup: true
      delayedStart: 40s
      period: 15m
